name: movieapplication
description: A Flutter Movies Database App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.9.0
  retrofit: ^4.7.1
  json_annotation: ^4.1.0

  # State management
  provider: ^6.0.5

  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # Utilities
  connectivity_plus: ^6.1.5
  share_plus: ^11.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  win32: ^5.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  retrofit_generator: ^8.1.2

flutter:
  uses-material-design: true